### ISSUE TITLE
Please remove dependencies on **rgdal**, **rgeos**, and/or **maptools**

### ISSUE THREAD

**Issue by rsbivand** [bluegreen-labs/hwsdr#3]
This package depends on (depends, imports or suggests) **raster** and one or more of the retiring packages **rgdal**, **rgeos** or **maptools** (https://r-spatial.org/r/2022/04/12/evolution.html, https://r-spatial.org/r/2022/12/14/evolution2.html). Since **raster** `3.6.3`, all use of external FOSS library functionality has been transferred to **terra**, making the retiring packages very likely redundant. It would help greatly if you could remove dependencies on the retiring packages as soon as possible.

**Comment by khufkens** [comment]
Fixed as per https://github.com/bluegreen-labs/hwsdr/commit/e6d81a7b2e0e14826c7aa2f62f7e4de5e4024547 will push new version to CRAN next year (will close then).

**Comment by rsbivand** [comment]
Thanks, on my `CMD check` set-up without retiring packages on the library path, things look fine: 
[00check.log](https://github.com/bluegreen-labs/hwsdr/files/12274538/00check.log)

**Comment by khufkens** [comment]
@rsbivand thanks for the check. This has been on the back burner, as I needed time to add some additional features. Anyway, this all works out now. Will submit this later after increasing unit tests / code coverage for new functions. Thanks for checking again.
